# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/boxes', type: :request do
  # Box. As you add validations to Box, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { code: '2222', location: 'E3', box_type: 'type1', status: 'active',
      min_products: 1, max_products: 1, created_by_id: 1, updated_by_id: 1 }
  end

  let(:invalid_attributes) do
    { location: nil }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Box.create! valid_attributes
      get boxes_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      box = Box.create! valid_attributes
      get box_url(box)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_box_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      box = Box.create! valid_attributes
      get edit_box_url(box)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Box' do
        expect do
          post boxes_url, params: { box: valid_attributes }
        end.to change(Box, :count).by(1)
      end

      it 'redirects to the created box' do
        post boxes_url, params: { box: valid_attributes }
        expect(response).to redirect_to(box_url(Box.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Box' do
        expect do
          post boxes_url, params: { box: invalid_attributes }
        end.to change(Box, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post boxes_url, params: { box: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested box' do
        box = Box.create! valid_attributes
        patch box_url(box), params: { box: new_attributes }
        box.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the box' do
        box = Box.create! valid_attributes
        patch box_url(box), params: { box: new_attributes }
        box.reload
        expect(response).to redirect_to(box_url(box))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        box = Box.create! valid_attributes
        patch box_url(box), params: { box: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested box' do
      box = Box.create! valid_attributes
      expect do
        delete box_url(box)
      end.to change(Box, :count).by(-1)
    end

    it 'redirects to the boxes list' do
      box = Box.create! valid_attributes
      delete box_url(box)
      expect(response).to redirect_to(boxes_url)
    end
  end
end
