# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/incidents', type: :request do
  # Incident. As you add validations to Incident, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { customer_id: 1, box_id: 1, user_id: 1, status: 'active', created_by_id: 1, updated_by_id: 1 }
  end

  let(:invalid_attributes) do
    { box_id: nil }
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_incident_url
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Incident' do
        expect do
          post incidents_url, params: { incident: valid_attributes }
        end.to change(Incident, :count).by(1)
      end

      it 'redirects to the created incident' do
        post incidents_url, params: { incident: valid_attributes }
        expect(response).to redirect_to(incident_url(Incident.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Incident' do
        expect do
          post incidents_url, params: { incident: invalid_attributes }
        end.to change(Incident, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post incidents_url, params: { incident: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end
end
